# Setup
title:        ML Summer Workshop @ KAIST
baseurl:      ""
paginate:     1
locale:       "en"
theme: jekyll-theme-cayman

# About/contact
author:
  name:       ML
  url:        https://mlworkshop-kaist.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
